### ISSUE TITLE
License?

### ISSUE THREAD

**Issue by hughesjj** [florianwiech/remix-aws-cdk-example#3]
Hey, I've been looking for exactly something like this but don't want to "IP Contaminate" myself by reading through it.

Do you intend to license this example [under](https://docs.github.com/en/communities/setting-up-your-project-for-healthy-contributions/adding-a-license-to-a-repository) MIT/similar permissive license?

**Comment by fwiech** [comment]
Hi, thank you that was indeed missing.
I just added the MIT license: https://github.com/florianwiech/remix-aws-cdk-example/commit/316a1538a2b8006c745ed691ae2925d024c4efc2
